# Generated by Django 5.0.3 on 2024-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithroles',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
